// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    public static class GetVappOrgNetwork
    {
        /// <summary>
        /// Provides a data source for VMware Cloud Director Org network attached to vApp. This can be used to access vApp Org VDC network.
        /// 
        /// Supported in provider *v2.7+*
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vcd = Pulumi.Vcd;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var web = Vcd.GetVapp.Invoke(new()
        ///     {
        ///         Name = "web",
        ///     });
        /// 
        ///     var network1 = Vcd.GetVappOrgNetwork.Invoke(new()
        ///     {
        ///         VappName = web.Apply(getVappResult =&gt; getVappResult.Name),
        ///         OrgNetworkName = "my-vapp-org-network",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["id"] = network1VcdVappNetwork.Id,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetVappOrgNetworkResult> InvokeAsync(GetVappOrgNetworkArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVappOrgNetworkResult>("vcd:index/getVappOrgNetwork:getVappOrgNetwork", args ?? new GetVappOrgNetworkArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a data source for VMware Cloud Director Org network attached to vApp. This can be used to access vApp Org VDC network.
        /// 
        /// Supported in provider *v2.7+*
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vcd = Pulumi.Vcd;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var web = Vcd.GetVapp.Invoke(new()
        ///     {
        ///         Name = "web",
        ///     });
        /// 
        ///     var network1 = Vcd.GetVappOrgNetwork.Invoke(new()
        ///     {
        ///         VappName = web.Apply(getVappResult =&gt; getVappResult.Name),
        ///         OrgNetworkName = "my-vapp-org-network",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["id"] = network1VcdVappNetwork.Id,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetVappOrgNetworkResult> Invoke(GetVappOrgNetworkInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVappOrgNetworkResult>("vcd:index/getVappOrgNetwork:getVappOrgNetwork", args ?? new GetVappOrgNetworkInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a data source for VMware Cloud Director Org network attached to vApp. This can be used to access vApp Org VDC network.
        /// 
        /// Supported in provider *v2.7+*
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Vcd = Pulumi.Vcd;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var web = Vcd.GetVapp.Invoke(new()
        ///     {
        ///         Name = "web",
        ///     });
        /// 
        ///     var network1 = Vcd.GetVappOrgNetwork.Invoke(new()
        ///     {
        ///         VappName = web.Apply(getVappResult =&gt; getVappResult.Name),
        ///         OrgNetworkName = "my-vapp-org-network",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["id"] = network1VcdVappNetwork.Id,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetVappOrgNetworkResult> Invoke(GetVappOrgNetworkInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetVappOrgNetworkResult>("vcd:index/getVappOrgNetwork:getVappOrgNetwork", args ?? new GetVappOrgNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVappOrgNetworkArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organisations
        /// </summary>
        [Input("org")]
        public string? Org { get; set; }

        /// <summary>
        /// A name for the vApp Org network, unique within the vApp.
        /// </summary>
        [Input("orgNetworkName", required: true)]
        public string OrgNetworkName { get; set; } = null!;

        /// <summary>
        /// The vApp name.
        /// </summary>
        [Input("vappName", required: true)]
        public string VappName { get; set; } = null!;

        /// <summary>
        /// The name of VDC to use, optional if defined at provider level
        /// </summary>
        [Input("vdc")]
        public string? Vdc { get; set; }

        public GetVappOrgNetworkArgs()
        {
        }
        public static new GetVappOrgNetworkArgs Empty => new GetVappOrgNetworkArgs();
    }

    public sealed class GetVappOrgNetworkInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organisations
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        /// <summary>
        /// A name for the vApp Org network, unique within the vApp.
        /// </summary>
        [Input("orgNetworkName", required: true)]
        public Input<string> OrgNetworkName { get; set; } = null!;

        /// <summary>
        /// The vApp name.
        /// </summary>
        [Input("vappName", required: true)]
        public Input<string> VappName { get; set; } = null!;

        /// <summary>
        /// The name of VDC to use, optional if defined at provider level
        /// </summary>
        [Input("vdc")]
        public Input<string>? Vdc { get; set; }

        public GetVappOrgNetworkInvokeArgs()
        {
        }
        public static new GetVappOrgNetworkInvokeArgs Empty => new GetVappOrgNetworkInvokeArgs();
    }


    [OutputType]
    public sealed class GetVappOrgNetworkResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsFenced;
        public readonly string? Org;
        public readonly string OrgNetworkName;
        public readonly bool RetainIpMacEnabled;
        public readonly string VappName;
        public readonly string? Vdc;

        [OutputConstructor]
        private GetVappOrgNetworkResult(
            string id,

            bool isFenced,

            string? org,

            string orgNetworkName,

            bool retainIpMacEnabled,

            string vappName,

            string? vdc)
        {
            Id = id;
            IsFenced = isFenced;
            Org = org;
            OrgNetworkName = orgNetworkName;
            RetainIpMacEnabled = retainIpMacEnabled;
            VappName = vappName;
            Vdc = vdc;
        }
    }
}
