// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    [VcdResourceType("vcd:index/nsxtEdgegatewayDhcpForwarding:NsxtEdgegatewayDhcpForwarding")]
    public partial class NsxtEdgegatewayDhcpForwarding : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IP addresses of DHCP servers. Maximum 8 can be specified.
        /// 
        /// &gt; Modification of the `dhcp_servers` field will not be changed in VCD when `enabled = false` because VCD API ignores DHCP server changes when DHCP forwarding is disabled.
        /// </summary>
        [Output("dhcpServers")]
        public Output<ImmutableArray<string>> DhcpServers { get; private set; } = null!;

        /// <summary>
        /// NSX-T Edge Gateway ID.
        /// </summary>
        [Output("edgeGatewayId")]
        public Output<string> EdgeGatewayId { get; private set; } = null!;

        /// <summary>
        /// DHCP Forwarding status.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Org in which the NSX-T Edge Gateway is located, required
        /// if not set in the provider section.
        /// </summary>
        [Output("org")]
        public Output<string?> Org { get; private set; } = null!;


        /// <summary>
        /// Create a NsxtEdgegatewayDhcpForwarding resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NsxtEdgegatewayDhcpForwarding(string name, NsxtEdgegatewayDhcpForwardingArgs args, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtEdgegatewayDhcpForwarding:NsxtEdgegatewayDhcpForwarding", name, args ?? new NsxtEdgegatewayDhcpForwardingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NsxtEdgegatewayDhcpForwarding(string name, Input<string> id, NsxtEdgegatewayDhcpForwardingState? state = null, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtEdgegatewayDhcpForwarding:NsxtEdgegatewayDhcpForwarding", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/vmware/terraform-provider-vcd/releases/download/v3.14.1/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NsxtEdgegatewayDhcpForwarding resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NsxtEdgegatewayDhcpForwarding Get(string name, Input<string> id, NsxtEdgegatewayDhcpForwardingState? state = null, CustomResourceOptions? options = null)
        {
            return new NsxtEdgegatewayDhcpForwarding(name, id, state, options);
        }
    }

    public sealed class NsxtEdgegatewayDhcpForwardingArgs : global::Pulumi.ResourceArgs
    {
        [Input("dhcpServers", required: true)]
        private InputList<string>? _dhcpServers;

        /// <summary>
        /// IP addresses of DHCP servers. Maximum 8 can be specified.
        /// 
        /// &gt; Modification of the `dhcp_servers` field will not be changed in VCD when `enabled = false` because VCD API ignores DHCP server changes when DHCP forwarding is disabled.
        /// </summary>
        public InputList<string> DhcpServers
        {
            get => _dhcpServers ?? (_dhcpServers = new InputList<string>());
            set => _dhcpServers = value;
        }

        /// <summary>
        /// NSX-T Edge Gateway ID.
        /// </summary>
        [Input("edgeGatewayId", required: true)]
        public Input<string> EdgeGatewayId { get; set; } = null!;

        /// <summary>
        /// DHCP Forwarding status.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Org in which the NSX-T Edge Gateway is located, required
        /// if not set in the provider section.
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        public NsxtEdgegatewayDhcpForwardingArgs()
        {
        }
        public static new NsxtEdgegatewayDhcpForwardingArgs Empty => new NsxtEdgegatewayDhcpForwardingArgs();
    }

    public sealed class NsxtEdgegatewayDhcpForwardingState : global::Pulumi.ResourceArgs
    {
        [Input("dhcpServers")]
        private InputList<string>? _dhcpServers;

        /// <summary>
        /// IP addresses of DHCP servers. Maximum 8 can be specified.
        /// 
        /// &gt; Modification of the `dhcp_servers` field will not be changed in VCD when `enabled = false` because VCD API ignores DHCP server changes when DHCP forwarding is disabled.
        /// </summary>
        public InputList<string> DhcpServers
        {
            get => _dhcpServers ?? (_dhcpServers = new InputList<string>());
            set => _dhcpServers = value;
        }

        /// <summary>
        /// NSX-T Edge Gateway ID.
        /// </summary>
        [Input("edgeGatewayId")]
        public Input<string>? EdgeGatewayId { get; set; }

        /// <summary>
        /// DHCP Forwarding status.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Org in which the NSX-T Edge Gateway is located, required
        /// if not set in the provider section.
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        public NsxtEdgegatewayDhcpForwardingState()
        {
        }
        public static new NsxtEdgegatewayDhcpForwardingState Empty => new NsxtEdgegatewayDhcpForwardingState();
    }
}
