// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd
{
    [VcdResourceType("vcd:index/nsxtAlbPool:NsxtAlbPool")]
    public partial class NsxtAlbPool : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Optional algorithm for choosing pool members (default `LEAST_CONNECTIONS`). Other options
        /// contain `ROUND_ROBIN`, `CONSISTENT_HASH` (uses Source IP Address hash), `FASTEST_RESPONSE`, `LEAST_LOAD`,
        /// `FEWEST_SERVERS`, `RANDOM`, `FEWEST_TASKS`, `CORE_AFFINITY`
        /// </summary>
        [Output("algorithm")]
        public Output<string?> Algorithm { get; private set; } = null!;

        /// <summary>
        /// A set of associated Virtual Service IDs
        /// </summary>
        [Output("associatedVirtualServiceIds")]
        public Output<ImmutableArray<string>> AssociatedVirtualServiceIds { get; private set; } = null!;

        /// <summary>
        /// A set of associated Virtual Service names
        /// </summary>
        [Output("associatedVirtualServices")]
        public Output<ImmutableArray<string>> AssociatedVirtualServices { get; private set; } = null!;

        /// <summary>
        /// A set of CA Certificates to be used when validating certificates presented by the
        /// pool members. Can be looked up using
        /// [vcd.LibraryCertificate](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/library_certificate) data source
        /// </summary>
        [Output("caCertificateIds")]
        public Output<ImmutableArray<string>> CaCertificateIds { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to check the common name of the certificate presented by the pool
        /// member
        /// </summary>
        [Output("cnCheckEnabled")]
        public Output<bool?> CnCheckEnabled { get; private set; } = null!;

        /// <summary>
        /// Default Port defines destination server port used by the traffic sent to the member
        /// (default `80`)
        /// </summary>
        [Output("defaultPort")]
        public Output<int?> DefaultPort { get; private set; } = null!;

        /// <summary>
        /// An optional description ALB Pool
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// A set of domain names which will be used to verify the common names or subject alternative
        /// names presented by the pool member certificates. It is performed only when common name check `cn_check_enabled` is
        /// enabled
        /// </summary>
        [Output("domainNames")]
        public Output<ImmutableArray<string>> DomainNames { get; private set; } = null!;

        /// <summary>
        /// An ID of NSX-T Edge Gateway. Can be looked up using
        /// [vcd.NsxtEdgegateway](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/nsxt_edgegateway) data source
        /// </summary>
        [Output("edgeGatewayId")]
        public Output<string> EdgeGatewayId { get; private set; } = null!;

        /// <summary>
        /// Boolean value if ALB Pool should be enabled (default `true`)
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        /// <summary>
        /// Number of enabled members defined in the Pool
        /// </summary>
        [Output("enabledMemberCount")]
        public Output<int> EnabledMemberCount { get; private set; } = null!;

        /// <summary>
        /// Maximum time in minutes to gracefully disable pool member (default `1`). Special
        /// values are `0` (immediate) and `-1` (infinite)
        /// </summary>
        [Output("gracefulTimeoutPeriod")]
        public Output<int?> GracefulTimeoutPeriod { get; private set; } = null!;

        /// <summary>
        /// Health message of ALB Pool
        /// </summary>
        [Output("healthMessage")]
        public Output<string> HealthMessage { get; private set; } = null!;

        /// <summary>
        /// A block to define health monitor. Multiple can be used. See Health
        /// monitor and example for usage details.
        /// 
        /// &lt;a id="member-block"&gt;&lt;/a&gt;
        /// </summary>
        [Output("healthMonitors")]
        public Output<ImmutableArray<Outputs.NsxtAlbPoolHealthMonitor>> HealthMonitors { get; private set; } = null!;

        /// <summary>
        /// Total number of members defined in the Pool
        /// </summary>
        [Output("memberCount")]
        public Output<int> MemberCount { get; private set; } = null!;

        /// <summary>
        /// A reference to NSX-T IP Set (`vcd.NsxtIpSet`).
        /// **Note** only one of `member`, `member_group_id` can be specified.
        /// </summary>
        [Output("memberGroupId")]
        public Output<string?> MemberGroupId { get; private set; } = null!;

        /// <summary>
        /// A block to define pool members. Multiple can be used. See
        /// Member and example for usage details. **Note** only one of `member`,
        /// `member_group_id` can be specified.
        /// </summary>
        [Output("members")]
        public Output<ImmutableArray<Outputs.NsxtAlbPoolMember>> Members { get; private set; } = null!;

        /// <summary>
        /// A name for ALB Pool
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful
        /// when connected as sysadmin working across different organisations.
        /// </summary>
        [Output("org")]
        public Output<string?> Org { get; private set; } = null!;

        /// <summary>
        /// defines if client traffic should be used to check if pool member is up or down
        /// (default `true`)
        /// </summary>
        [Output("passiveMonitoringEnabled")]
        public Output<bool?> PassiveMonitoringEnabled { get; private set; } = null!;

        /// <summary>
        /// Persistence profile will ensure that the same user sticks to the same server for a
        /// desired duration of time. If the persistence profile is unmanaged by Cloud Director, updates that leave the values
        /// unchanged will continue to use the same unmanaged profile. Any changes made to the persistence profile will cause
        /// Cloud Director to switch the pool to a profile managed by Cloud Director. See Persistence
        /// profile and example for usage details.
        /// </summary>
        [Output("persistenceProfile")]
        public Output<Outputs.NsxtAlbPoolPersistenceProfile?> PersistenceProfile { get; private set; } = null!;

        /// <summary>
        /// Enables SSL - Will be turned on automatically when CA certificates are used
        /// </summary>
        [Output("sslEnabled")]
        public Output<bool> SslEnabled { get; private set; } = null!;

        /// <summary>
        /// Number of members defined in the Pool that are accepting traffic
        /// </summary>
        [Output("upMemberCount")]
        public Output<int> UpMemberCount { get; private set; } = null!;

        /// <summary>
        /// The name of VDC to use, optional if defined at provider level
        /// </summary>
        [Output("vdc")]
        public Output<string> Vdc { get; private set; } = null!;


        /// <summary>
        /// Create a NsxtAlbPool resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NsxtAlbPool(string name, NsxtAlbPoolArgs args, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtAlbPool:NsxtAlbPool", name, args ?? new NsxtAlbPoolArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NsxtAlbPool(string name, Input<string> id, NsxtAlbPoolState? state = null, CustomResourceOptions? options = null)
            : base("vcd:index/nsxtAlbPool:NsxtAlbPool", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/vmware/terraform-provider-vcd/releases/download/v3.14.1/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NsxtAlbPool resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NsxtAlbPool Get(string name, Input<string> id, NsxtAlbPoolState? state = null, CustomResourceOptions? options = null)
        {
            return new NsxtAlbPool(name, id, state, options);
        }
    }

    public sealed class NsxtAlbPoolArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional algorithm for choosing pool members (default `LEAST_CONNECTIONS`). Other options
        /// contain `ROUND_ROBIN`, `CONSISTENT_HASH` (uses Source IP Address hash), `FASTEST_RESPONSE`, `LEAST_LOAD`,
        /// `FEWEST_SERVERS`, `RANDOM`, `FEWEST_TASKS`, `CORE_AFFINITY`
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        [Input("caCertificateIds")]
        private InputList<string>? _caCertificateIds;

        /// <summary>
        /// A set of CA Certificates to be used when validating certificates presented by the
        /// pool members. Can be looked up using
        /// [vcd.LibraryCertificate](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/library_certificate) data source
        /// </summary>
        public InputList<string> CaCertificateIds
        {
            get => _caCertificateIds ?? (_caCertificateIds = new InputList<string>());
            set => _caCertificateIds = value;
        }

        /// <summary>
        /// Specifies whether to check the common name of the certificate presented by the pool
        /// member
        /// </summary>
        [Input("cnCheckEnabled")]
        public Input<bool>? CnCheckEnabled { get; set; }

        /// <summary>
        /// Default Port defines destination server port used by the traffic sent to the member
        /// (default `80`)
        /// </summary>
        [Input("defaultPort")]
        public Input<int>? DefaultPort { get; set; }

        /// <summary>
        /// An optional description ALB Pool
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domainNames")]
        private InputList<string>? _domainNames;

        /// <summary>
        /// A set of domain names which will be used to verify the common names or subject alternative
        /// names presented by the pool member certificates. It is performed only when common name check `cn_check_enabled` is
        /// enabled
        /// </summary>
        public InputList<string> DomainNames
        {
            get => _domainNames ?? (_domainNames = new InputList<string>());
            set => _domainNames = value;
        }

        /// <summary>
        /// An ID of NSX-T Edge Gateway. Can be looked up using
        /// [vcd.NsxtEdgegateway](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/nsxt_edgegateway) data source
        /// </summary>
        [Input("edgeGatewayId", required: true)]
        public Input<string> EdgeGatewayId { get; set; } = null!;

        /// <summary>
        /// Boolean value if ALB Pool should be enabled (default `true`)
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Maximum time in minutes to gracefully disable pool member (default `1`). Special
        /// values are `0` (immediate) and `-1` (infinite)
        /// </summary>
        [Input("gracefulTimeoutPeriod")]
        public Input<int>? GracefulTimeoutPeriod { get; set; }

        [Input("healthMonitors")]
        private InputList<Inputs.NsxtAlbPoolHealthMonitorArgs>? _healthMonitors;

        /// <summary>
        /// A block to define health monitor. Multiple can be used. See Health
        /// monitor and example for usage details.
        /// 
        /// &lt;a id="member-block"&gt;&lt;/a&gt;
        /// </summary>
        public InputList<Inputs.NsxtAlbPoolHealthMonitorArgs> HealthMonitors
        {
            get => _healthMonitors ?? (_healthMonitors = new InputList<Inputs.NsxtAlbPoolHealthMonitorArgs>());
            set => _healthMonitors = value;
        }

        /// <summary>
        /// A reference to NSX-T IP Set (`vcd.NsxtIpSet`).
        /// **Note** only one of `member`, `member_group_id` can be specified.
        /// </summary>
        [Input("memberGroupId")]
        public Input<string>? MemberGroupId { get; set; }

        [Input("members")]
        private InputList<Inputs.NsxtAlbPoolMemberArgs>? _members;

        /// <summary>
        /// A block to define pool members. Multiple can be used. See
        /// Member and example for usage details. **Note** only one of `member`,
        /// `member_group_id` can be specified.
        /// </summary>
        public InputList<Inputs.NsxtAlbPoolMemberArgs> Members
        {
            get => _members ?? (_members = new InputList<Inputs.NsxtAlbPoolMemberArgs>());
            set => _members = value;
        }

        /// <summary>
        /// A name for ALB Pool
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful
        /// when connected as sysadmin working across different organisations.
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        /// <summary>
        /// defines if client traffic should be used to check if pool member is up or down
        /// (default `true`)
        /// </summary>
        [Input("passiveMonitoringEnabled")]
        public Input<bool>? PassiveMonitoringEnabled { get; set; }

        /// <summary>
        /// Persistence profile will ensure that the same user sticks to the same server for a
        /// desired duration of time. If the persistence profile is unmanaged by Cloud Director, updates that leave the values
        /// unchanged will continue to use the same unmanaged profile. Any changes made to the persistence profile will cause
        /// Cloud Director to switch the pool to a profile managed by Cloud Director. See Persistence
        /// profile and example for usage details.
        /// </summary>
        [Input("persistenceProfile")]
        public Input<Inputs.NsxtAlbPoolPersistenceProfileArgs>? PersistenceProfile { get; set; }

        /// <summary>
        /// Enables SSL - Will be turned on automatically when CA certificates are used
        /// </summary>
        [Input("sslEnabled")]
        public Input<bool>? SslEnabled { get; set; }

        /// <summary>
        /// The name of VDC to use, optional if defined at provider level
        /// </summary>
        [Input("vdc")]
        public Input<string>? Vdc { get; set; }

        public NsxtAlbPoolArgs()
        {
        }
        public static new NsxtAlbPoolArgs Empty => new NsxtAlbPoolArgs();
    }

    public sealed class NsxtAlbPoolState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional algorithm for choosing pool members (default `LEAST_CONNECTIONS`). Other options
        /// contain `ROUND_ROBIN`, `CONSISTENT_HASH` (uses Source IP Address hash), `FASTEST_RESPONSE`, `LEAST_LOAD`,
        /// `FEWEST_SERVERS`, `RANDOM`, `FEWEST_TASKS`, `CORE_AFFINITY`
        /// </summary>
        [Input("algorithm")]
        public Input<string>? Algorithm { get; set; }

        [Input("associatedVirtualServiceIds")]
        private InputList<string>? _associatedVirtualServiceIds;

        /// <summary>
        /// A set of associated Virtual Service IDs
        /// </summary>
        public InputList<string> AssociatedVirtualServiceIds
        {
            get => _associatedVirtualServiceIds ?? (_associatedVirtualServiceIds = new InputList<string>());
            set => _associatedVirtualServiceIds = value;
        }

        [Input("associatedVirtualServices")]
        private InputList<string>? _associatedVirtualServices;

        /// <summary>
        /// A set of associated Virtual Service names
        /// </summary>
        public InputList<string> AssociatedVirtualServices
        {
            get => _associatedVirtualServices ?? (_associatedVirtualServices = new InputList<string>());
            set => _associatedVirtualServices = value;
        }

        [Input("caCertificateIds")]
        private InputList<string>? _caCertificateIds;

        /// <summary>
        /// A set of CA Certificates to be used when validating certificates presented by the
        /// pool members. Can be looked up using
        /// [vcd.LibraryCertificate](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/library_certificate) data source
        /// </summary>
        public InputList<string> CaCertificateIds
        {
            get => _caCertificateIds ?? (_caCertificateIds = new InputList<string>());
            set => _caCertificateIds = value;
        }

        /// <summary>
        /// Specifies whether to check the common name of the certificate presented by the pool
        /// member
        /// </summary>
        [Input("cnCheckEnabled")]
        public Input<bool>? CnCheckEnabled { get; set; }

        /// <summary>
        /// Default Port defines destination server port used by the traffic sent to the member
        /// (default `80`)
        /// </summary>
        [Input("defaultPort")]
        public Input<int>? DefaultPort { get; set; }

        /// <summary>
        /// An optional description ALB Pool
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domainNames")]
        private InputList<string>? _domainNames;

        /// <summary>
        /// A set of domain names which will be used to verify the common names or subject alternative
        /// names presented by the pool member certificates. It is performed only when common name check `cn_check_enabled` is
        /// enabled
        /// </summary>
        public InputList<string> DomainNames
        {
            get => _domainNames ?? (_domainNames = new InputList<string>());
            set => _domainNames = value;
        }

        /// <summary>
        /// An ID of NSX-T Edge Gateway. Can be looked up using
        /// [vcd.NsxtEdgegateway](https://www.terraform.io/providers/vmware/vcd/latest/docs/data-sources/nsxt_edgegateway) data source
        /// </summary>
        [Input("edgeGatewayId")]
        public Input<string>? EdgeGatewayId { get; set; }

        /// <summary>
        /// Boolean value if ALB Pool should be enabled (default `true`)
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Number of enabled members defined in the Pool
        /// </summary>
        [Input("enabledMemberCount")]
        public Input<int>? EnabledMemberCount { get; set; }

        /// <summary>
        /// Maximum time in minutes to gracefully disable pool member (default `1`). Special
        /// values are `0` (immediate) and `-1` (infinite)
        /// </summary>
        [Input("gracefulTimeoutPeriod")]
        public Input<int>? GracefulTimeoutPeriod { get; set; }

        /// <summary>
        /// Health message of ALB Pool
        /// </summary>
        [Input("healthMessage")]
        public Input<string>? HealthMessage { get; set; }

        [Input("healthMonitors")]
        private InputList<Inputs.NsxtAlbPoolHealthMonitorGetArgs>? _healthMonitors;

        /// <summary>
        /// A block to define health monitor. Multiple can be used. See Health
        /// monitor and example for usage details.
        /// 
        /// &lt;a id="member-block"&gt;&lt;/a&gt;
        /// </summary>
        public InputList<Inputs.NsxtAlbPoolHealthMonitorGetArgs> HealthMonitors
        {
            get => _healthMonitors ?? (_healthMonitors = new InputList<Inputs.NsxtAlbPoolHealthMonitorGetArgs>());
            set => _healthMonitors = value;
        }

        /// <summary>
        /// Total number of members defined in the Pool
        /// </summary>
        [Input("memberCount")]
        public Input<int>? MemberCount { get; set; }

        /// <summary>
        /// A reference to NSX-T IP Set (`vcd.NsxtIpSet`).
        /// **Note** only one of `member`, `member_group_id` can be specified.
        /// </summary>
        [Input("memberGroupId")]
        public Input<string>? MemberGroupId { get; set; }

        [Input("members")]
        private InputList<Inputs.NsxtAlbPoolMemberGetArgs>? _members;

        /// <summary>
        /// A block to define pool members. Multiple can be used. See
        /// Member and example for usage details. **Note** only one of `member`,
        /// `member_group_id` can be specified.
        /// </summary>
        public InputList<Inputs.NsxtAlbPoolMemberGetArgs> Members
        {
            get => _members ?? (_members = new InputList<Inputs.NsxtAlbPoolMemberGetArgs>());
            set => _members = value;
        }

        /// <summary>
        /// A name for ALB Pool
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of organization to use, optional if defined at provider level. Useful
        /// when connected as sysadmin working across different organisations.
        /// </summary>
        [Input("org")]
        public Input<string>? Org { get; set; }

        /// <summary>
        /// defines if client traffic should be used to check if pool member is up or down
        /// (default `true`)
        /// </summary>
        [Input("passiveMonitoringEnabled")]
        public Input<bool>? PassiveMonitoringEnabled { get; set; }

        /// <summary>
        /// Persistence profile will ensure that the same user sticks to the same server for a
        /// desired duration of time. If the persistence profile is unmanaged by Cloud Director, updates that leave the values
        /// unchanged will continue to use the same unmanaged profile. Any changes made to the persistence profile will cause
        /// Cloud Director to switch the pool to a profile managed by Cloud Director. See Persistence
        /// profile and example for usage details.
        /// </summary>
        [Input("persistenceProfile")]
        public Input<Inputs.NsxtAlbPoolPersistenceProfileGetArgs>? PersistenceProfile { get; set; }

        /// <summary>
        /// Enables SSL - Will be turned on automatically when CA certificates are used
        /// </summary>
        [Input("sslEnabled")]
        public Input<bool>? SslEnabled { get; set; }

        /// <summary>
        /// Number of members defined in the Pool that are accepting traffic
        /// </summary>
        [Input("upMemberCount")]
        public Input<int>? UpMemberCount { get; set; }

        /// <summary>
        /// The name of VDC to use, optional if defined at provider level
        /// </summary>
        [Input("vdc")]
        public Input<string>? Vdc { get; set; }

        public NsxtAlbPoolState()
        {
        }
        public static new NsxtAlbPoolState Empty => new NsxtAlbPoolState();
    }
}
