// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class GetNsxtNetworkDhcpBindingDhcpV4ConfigResult
    {
        /// <summary>
        /// Gateway IP address to be used by the DHCP client
        /// </summary>
        public readonly string GatewayIpAddress;
        /// <summary>
        /// Hostname to be used by the DHCP client
        /// </summary>
        public readonly string Hostname;

        [OutputConstructor]
        private GetNsxtNetworkDhcpBindingDhcpV4ConfigResult(
            string gatewayIpAddress,

            string hostname)
        {
            GatewayIpAddress = gatewayIpAddress;
            Hostname = hostname;
        }
    }
}
