// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class GetNsxtAlbVirtualServiceHttpRespRulesRuleMatchCriteriaLocationHeaderResult
    {
        /// <summary>
        /// Criteria to use for matching location header
        /// </summary>
        public readonly string Criteria;
        /// <summary>
        /// A set of values to match for criteria
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private GetNsxtAlbVirtualServiceHttpRespRulesRuleMatchCriteriaLocationHeaderResult(
            string criteria,

            ImmutableArray<string> values)
        {
            Criteria = criteria;
            Values = values;
        }
    }
}
