// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class NsxtEdgegatewaySubnet
    {
        /// <summary>
        /// Define one or more blocks to sub-allocate pools on the edge gateway
        /// </summary>
        public readonly ImmutableArray<Outputs.NsxtEdgegatewaySubnetAllocatedIp> AllocatedIps;
        /// <summary>
        /// Gateway address for a subnet
        /// </summary>
        public readonly string Gateway;
        /// <summary>
        /// Prefix length for a subnet (e.g. 24)
        /// </summary>
        public readonly int PrefixLength;
        /// <summary>
        /// Primary IP address exposed for an easy access without nesting.
        /// </summary>
        public readonly string? PrimaryIp;

        [OutputConstructor]
        private NsxtEdgegatewaySubnet(
            ImmutableArray<Outputs.NsxtEdgegatewaySubnetAllocatedIp> allocatedIps,

            string gateway,

            int prefixLength,

            string? primaryIp)
        {
            AllocatedIps = allocatedIps;
            Gateway = gateway;
            PrefixLength = prefixLength;
            PrimaryIp = primaryIp;
        }
    }
}
