// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class NsxtDynamicSecurityGroupCriteria
    {
        /// <summary>
        /// Up to 4 rules for matching VMs. List of rules are matched with boolean `AND`
        /// operation and all defines rules must match to include object. See Rule for rule
        /// definition structure.
        /// 
        /// 
        /// &lt;a id="rule"&gt;&lt;/a&gt;
        /// </summary>
        public readonly ImmutableArray<Outputs.NsxtDynamicSecurityGroupCriteriaRule> Rules;

        [OutputConstructor]
        private NsxtDynamicSecurityGroupCriteria(ImmutableArray<Outputs.NsxtDynamicSecurityGroupCriteriaRule> rules)
        {
            Rules = rules;
        }
    }
}
