// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Outputs
{

    [OutputType]
    public sealed class SolutionLandingZoneCatalog
    {
        /// <summary>
        /// Capability set for catalog
        /// </summary>
        public readonly ImmutableArray<string> Capabilities;
        /// <summary>
        /// ID of catalog
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Catalog Name
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private SolutionLandingZoneCatalog(
            ImmutableArray<string> capabilities,

            string id,

            string? name)
        {
            Capabilities = capabilities;
            Id = id;
            Name = name;
        }
    }
}
