// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/ergSey/pulumi-vcd/sdk/go/vcd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Supported in provider *v3.3+* and VCD 10.1+ with NSX-T backed Edge Gateways.
//
// Provides a data source to read NSX-T Firewall configuration of an Edge Gateway. Firewalls allow
// user to control the incoming and outgoing network traffic to and from an NSX-T Data Center
// Edge Gateway.
//
// ## Example Usage
//
// ### Read A List Of Firewall Rules On Edge Gateway)
// ```go
// package main
//
// import (
//
//	"github.com/ergSey/pulumi-vcd/sdk/go/vcd"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := vcd.LookupNsxtFirewall(ctx, &vcd.LookupNsxtFirewallArgs{
//				Org:           pulumi.StringRef("my-org"),
//				EdgeGatewayId: testingVcdNsxtEdgegateway.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupNsxtFirewall(ctx *pulumi.Context, args *LookupNsxtFirewallArgs, opts ...pulumi.InvokeOption) (*LookupNsxtFirewallResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNsxtFirewallResult
	err := ctx.Invoke("vcd:index/getNsxtFirewall:getNsxtFirewall", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNsxtFirewall.
type LookupNsxtFirewallArgs struct {
	// The ID of the Edge Gateway (NSX-T only). Can be looked up using
	// `NsxtEdgegateway` data source
	EdgeGatewayId string `pulumi:"edgeGatewayId"`
	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organizations.
	Org *string `pulumi:"org"`
	// Deprecated: Edge Gateway will be looked up based on 'edge_gateway_id' field
	Vdc *string `pulumi:"vdc"`
}

// A collection of values returned by getNsxtFirewall.
type LookupNsxtFirewallResult struct {
	EdgeGatewayId string `pulumi:"edgeGatewayId"`
	// The provider-assigned unique ID for this managed resource.
	Id    string                `pulumi:"id"`
	Org   *string               `pulumi:"org"`
	Rules []GetNsxtFirewallRule `pulumi:"rules"`
	// Deprecated: Edge Gateway will be looked up based on 'edge_gateway_id' field
	Vdc *string `pulumi:"vdc"`
}

func LookupNsxtFirewallOutput(ctx *pulumi.Context, args LookupNsxtFirewallOutputArgs, opts ...pulumi.InvokeOption) LookupNsxtFirewallResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNsxtFirewallResultOutput, error) {
			args := v.(LookupNsxtFirewallArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("vcd:index/getNsxtFirewall:getNsxtFirewall", args, LookupNsxtFirewallResultOutput{}, options).(LookupNsxtFirewallResultOutput), nil
		}).(LookupNsxtFirewallResultOutput)
}

// A collection of arguments for invoking getNsxtFirewall.
type LookupNsxtFirewallOutputArgs struct {
	// The ID of the Edge Gateway (NSX-T only). Can be looked up using
	// `NsxtEdgegateway` data source
	EdgeGatewayId pulumi.StringInput `pulumi:"edgeGatewayId"`
	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organizations.
	Org pulumi.StringPtrInput `pulumi:"org"`
	// Deprecated: Edge Gateway will be looked up based on 'edge_gateway_id' field
	Vdc pulumi.StringPtrInput `pulumi:"vdc"`
}

func (LookupNsxtFirewallOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNsxtFirewallArgs)(nil)).Elem()
}

// A collection of values returned by getNsxtFirewall.
type LookupNsxtFirewallResultOutput struct{ *pulumi.OutputState }

func (LookupNsxtFirewallResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNsxtFirewallResult)(nil)).Elem()
}

func (o LookupNsxtFirewallResultOutput) ToLookupNsxtFirewallResultOutput() LookupNsxtFirewallResultOutput {
	return o
}

func (o LookupNsxtFirewallResultOutput) ToLookupNsxtFirewallResultOutputWithContext(ctx context.Context) LookupNsxtFirewallResultOutput {
	return o
}

func (o LookupNsxtFirewallResultOutput) EdgeGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNsxtFirewallResult) string { return v.EdgeGatewayId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNsxtFirewallResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNsxtFirewallResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNsxtFirewallResultOutput) Org() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNsxtFirewallResult) *string { return v.Org }).(pulumi.StringPtrOutput)
}

func (o LookupNsxtFirewallResultOutput) Rules() GetNsxtFirewallRuleArrayOutput {
	return o.ApplyT(func(v LookupNsxtFirewallResult) []GetNsxtFirewallRule { return v.Rules }).(GetNsxtFirewallRuleArrayOutput)
}

// Deprecated: Edge Gateway will be looked up based on 'edge_gateway_id' field
func (o LookupNsxtFirewallResultOutput) Vdc() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNsxtFirewallResult) *string { return v.Vdc }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNsxtFirewallResultOutput{})
}
