// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vcd

import (
	"context"
	"reflect"

	"github.com/ergSey/pulumi-vcd/sdk/go/vcd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Supported in provider *v3.10+*.
//
// Provides a data source to read SAML configuration for an organization.
//
// > **Note:** This data source requires system administrator privileges.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/ergSey/pulumi-vcd/sdk/go/vcd"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			my_org, err := vcd.LookupOrg(ctx, &vcd.LookupOrgArgs{
//				Name: "my-org",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = vcd.LookupOrgSaml(ctx, &vcd.LookupOrgSamlArgs{
//				OrgId: my_org.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupOrgSaml(ctx *pulumi.Context, args *LookupOrgSamlArgs, opts ...pulumi.InvokeOption) (*LookupOrgSamlResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrgSamlResult
	err := ctx.Invoke("vcd:index/getOrgSaml:getOrgSaml", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrgSaml.
type LookupOrgSamlArgs struct {
	// ID of the organization containing the SAML settings
	OrgId string `pulumi:"orgId"`
}

// A collection of values returned by getOrgSaml.
type LookupOrgSamlResult struct {
	// The name of the SAML attribute that returns the email address of the user
	Email string `pulumi:"email"`
	// Shows whether the SAML identity service is used for authentication
	Enabled bool `pulumi:"enabled"`
	// Your service provider entity ID
	EntityId string `pulumi:"entityId"`
	// The name of the SAML attribute that returns the first name of the user
	FirstName string `pulumi:"firstName"`
	// The name of the SAML attribute that returns the full name of the user
	FullName string `pulumi:"fullName"`
	// The name of the SAML attribute that returns the identifiers of all the groups of which the user is a member
	Group string `pulumi:"group"`
	// The provider-assigned unique ID for this managed resource.
	Id    string `pulumi:"id"`
	OrgId string `pulumi:"orgId"`
	// The name of the SAML attribute that returns the identifiers of all roles of the user
	Role string `pulumi:"role"`
	// The name of the SAML attribute that returns the surname of the user
	Surname string `pulumi:"surname"`
	// The name of the SAML attribute that returns the username of the user
	UserName string `pulumi:"userName"`
}

func LookupOrgSamlOutput(ctx *pulumi.Context, args LookupOrgSamlOutputArgs, opts ...pulumi.InvokeOption) LookupOrgSamlResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrgSamlResultOutput, error) {
			args := v.(LookupOrgSamlArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("vcd:index/getOrgSaml:getOrgSaml", args, LookupOrgSamlResultOutput{}, options).(LookupOrgSamlResultOutput), nil
		}).(LookupOrgSamlResultOutput)
}

// A collection of arguments for invoking getOrgSaml.
type LookupOrgSamlOutputArgs struct {
	// ID of the organization containing the SAML settings
	OrgId pulumi.StringInput `pulumi:"orgId"`
}

func (LookupOrgSamlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrgSamlArgs)(nil)).Elem()
}

// A collection of values returned by getOrgSaml.
type LookupOrgSamlResultOutput struct{ *pulumi.OutputState }

func (LookupOrgSamlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrgSamlResult)(nil)).Elem()
}

func (o LookupOrgSamlResultOutput) ToLookupOrgSamlResultOutput() LookupOrgSamlResultOutput {
	return o
}

func (o LookupOrgSamlResultOutput) ToLookupOrgSamlResultOutputWithContext(ctx context.Context) LookupOrgSamlResultOutput {
	return o
}

// The name of the SAML attribute that returns the email address of the user
func (o LookupOrgSamlResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.Email }).(pulumi.StringOutput)
}

// Shows whether the SAML identity service is used for authentication
func (o LookupOrgSamlResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Your service provider entity ID
func (o LookupOrgSamlResultOutput) EntityId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.EntityId }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the first name of the user
func (o LookupOrgSamlResultOutput) FirstName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.FirstName }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the full name of the user
func (o LookupOrgSamlResultOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.FullName }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the identifiers of all the groups of which the user is a member
func (o LookupOrgSamlResultOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.Group }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupOrgSamlResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupOrgSamlResultOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.OrgId }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the identifiers of all roles of the user
func (o LookupOrgSamlResultOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.Role }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the surname of the user
func (o LookupOrgSamlResultOutput) Surname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.Surname }).(pulumi.StringOutput)
}

// The name of the SAML attribute that returns the username of the user
func (o LookupOrgSamlResultOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgSamlResult) string { return v.UserName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrgSamlResultOutput{})
}
