// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vcd.Inputs
{

    public sealed class NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Set to true if the connection should be closed
        /// </summary>
        [Input("actionCloseConnection")]
        public Input<bool>? ActionCloseConnection { get; set; }

        [Input("actionLocalResponses")]
        private InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionLocalResponseArgs>? _actionLocalResponses;

        /// <summary>
        /// Send custom response
        /// </summary>
        public InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionLocalResponseArgs> ActionLocalResponses
        {
            get => _actionLocalResponses ?? (_actionLocalResponses = new InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionLocalResponseArgs>());
            set => _actionLocalResponses = value;
        }

        [Input("actionRedirects")]
        private InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionRedirectArgs>? _actionRedirects;

        /// <summary>
        /// Redirect based on rate limits
        /// </summary>
        public InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionRedirectArgs> ActionRedirects
        {
            get => _actionRedirects ?? (_actionRedirects = new InputList<Inputs.NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitActionRedirectArgs>());
            set => _actionRedirects = value;
        }

        /// <summary>
        /// Maximum number of connections, requests or packets permitted each period. The count must be between 1 and 1000000000
        /// </summary>
        [Input("count", required: true)]
        public Input<string> Count { get; set; } = null!;

        /// <summary>
        /// Time value in seconds to enforce rate count. The period must be between 1 and 1000000000
        /// </summary>
        [Input("period", required: true)]
        public Input<string> Period { get; set; } = null!;

        public NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitArgs()
        {
        }
        public static new NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitArgs Empty => new NsxtAlbVirtualServiceHttpSecRulesRuleActionsRateLimitArgs();
    }
}
