// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Supported in provider *v3.10+* and VCD 10.3.1+ with NSX-T.
 *
 * Provides a data source to read NSX-T Edge Gateway DHCP forwarding configuration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vcd from "@pulumi/vcd";
 *
 * const v1 = vcd.getOrgVdc({
 *     org: "datacloud",
 *     name: "nsxt-vdc-datacloud",
 * });
 * const testing_in_vdc = v1.then(v1 => vcd.getNsxtEdgegateway({
 *     org: "datacloud",
 *     ownerId: v1.id,
 *     name: "nsxt-gw-datacloud",
 * }));
 * const testing_in_vdcGetNsxtEdgegatewayDhcpForwarding = testing_in_vdc.then(testing_in_vdc => vcd.getNsxtEdgegatewayDhcpForwarding({
 *     org: "datacloud",
 *     edgeGatewayId: testing_in_vdc.id,
 * }));
 * ```
 */
export function getNsxtEdgegatewayDhcpForwarding(args: GetNsxtEdgegatewayDhcpForwardingArgs, opts?: pulumi.InvokeOptions): Promise<GetNsxtEdgegatewayDhcpForwardingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("vcd:index/getNsxtEdgegatewayDhcpForwarding:getNsxtEdgegatewayDhcpForwarding", {
        "edgeGatewayId": args.edgeGatewayId,
        "org": args.org,
    }, opts);
}

/**
 * A collection of arguments for invoking getNsxtEdgegatewayDhcpForwarding.
 */
export interface GetNsxtEdgegatewayDhcpForwardingArgs {
    /**
     * NSX-T Edge Gateway ID.
     */
    edgeGatewayId: string;
    /**
     * Org in which the NSX-T Edge Gateway is located, required
     * if not set in the provider section.
     */
    org?: string;
}

/**
 * A collection of values returned by getNsxtEdgegatewayDhcpForwarding.
 */
export interface GetNsxtEdgegatewayDhcpForwardingResult {
    readonly dhcpServers: string[];
    readonly edgeGatewayId: string;
    readonly enabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly org?: string;
}
/**
 * Supported in provider *v3.10+* and VCD 10.3.1+ with NSX-T.
 *
 * Provides a data source to read NSX-T Edge Gateway DHCP forwarding configuration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vcd from "@pulumi/vcd";
 *
 * const v1 = vcd.getOrgVdc({
 *     org: "datacloud",
 *     name: "nsxt-vdc-datacloud",
 * });
 * const testing_in_vdc = v1.then(v1 => vcd.getNsxtEdgegateway({
 *     org: "datacloud",
 *     ownerId: v1.id,
 *     name: "nsxt-gw-datacloud",
 * }));
 * const testing_in_vdcGetNsxtEdgegatewayDhcpForwarding = testing_in_vdc.then(testing_in_vdc => vcd.getNsxtEdgegatewayDhcpForwarding({
 *     org: "datacloud",
 *     edgeGatewayId: testing_in_vdc.id,
 * }));
 * ```
 */
export function getNsxtEdgegatewayDhcpForwardingOutput(args: GetNsxtEdgegatewayDhcpForwardingOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNsxtEdgegatewayDhcpForwardingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("vcd:index/getNsxtEdgegatewayDhcpForwarding:getNsxtEdgegatewayDhcpForwarding", {
        "edgeGatewayId": args.edgeGatewayId,
        "org": args.org,
    }, opts);
}

/**
 * A collection of arguments for invoking getNsxtEdgegatewayDhcpForwarding.
 */
export interface GetNsxtEdgegatewayDhcpForwardingOutputArgs {
    /**
     * NSX-T Edge Gateway ID.
     */
    edgeGatewayId: pulumi.Input<string>;
    /**
     * Org in which the NSX-T Edge Gateway is located, required
     * if not set in the provider section.
     */
    org?: pulumi.Input<string>;
}
